# Generated by Django 5.1.3 on 2024-11-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
