# Generated by Django 5.1.3 on 2024-12-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_user_review_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currently_reading',
            field=models.ForeignKey(default=32730, on_delete=django.db.models.deletion.CASCADE, to='project.book'),
            preserve_default=False,
        ),
    ]
