# Generated by Django 5.1.3 on 2024-12-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currently_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.book'),
        ),
    ]
