# Generated by Django 5.1.3 on 2024-12-08 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_user_person_rename_user_review_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.book')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.person')),
            ],
        ),
    ]
